const config = {
	APPWRITE_URL: import.meta.env.VITE_APPWRITE_URL,
	APPWRITE_PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
	APPWRITE_DATABASE_ID: import.meta.env.VITE_APPWRITE_DATABASE_ID,
	APPWRITE_ARTICLE_COLLECTION_ID: import.meta.env
		.VITE_APPWRITE_ARTICLE_COLLECTION_ID,
	APPWRITE_USER_COLLECTION_ID: import.meta.env
		.VITE_APPWRITE_USER_COLLECTION_ID,
	APPWRITE_BUCKET_ID: import.meta.env.VITE_APPWRITE_BUCKET_ID,
	TINYEDITOR_API: import.meta.env.VITE_TINYEDITOR_API,
};

export default config;
